ARGS:
 tab: 'Hi4D_TEST'
 num_views: 4
 dataset_rootdir: '/mnt/data/hi4d_dataset'
 output_dir: './dump/dinov2_baseline'
 eval_dataset: 'hi4d_test'
 GPUS: 0
 model_version: 1
 distributed_training: False

 mode: 'parsing'

 master_batch_size: -1
 val_batch_size: 1
 nw_eval: 2
 eval: True
 collision_aware_centermap: False
 collision_factor: 0.2
 calc_PVE_error: True

 backbone: 'dinov2'
 input_size: 448
 centermap_size: 32
 centermap_conf_thresh: 0.2
 max_person: 2

 model_path: /mnt/SKY/checkpoints/dinov2_cm32_dinov2_vanilla_on_gpu0,1_val/dinov2_cm32_dinov2_vanilla_70.pkl